%YAML 1.2
---
# Config  for my application
# --------------------------
optimizedGPS:
  foo: bar
  bar: [1, 2]
# Config for logging
# ------------------
# See http://docs.python.org/2.7/library/logging.config.html#configuration-dictionary-schema
logging:
  version: 1
  disable_existing_loggers: true
  # Configuring the default (root) logger is highly recommended
  root:
    level: !!python/name:logging.DEBUG
    handlers: [console]
  loggers:
    # Logging from my application
    structure.CongestionGPSGraph:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: structure.CongestionGPSGraph
    structure.GPSGraph:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: structure.GPSGraph
    structure.Node:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: structure.Node
    structure.Edge:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: structure.Edge
    tests.StructureTest:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: tests.StructureTest
    # Controlling logging of 3rd party libs
  handlers:
    logfile:
      class: logging.FileHandler
      filename: logs.log
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
  formatters:
    simpleFormatter:
      class: !!python/name:logging.Formatter
      format: '%(asctime)s %(filename)-30s %(levelname)-8s: %(message)s'
      datefmt: '%Y-%m-%dT%T%Z'
