%YAML 1.2
---
# Config  for my application
# --------------------------
optimizedGPS:
  foo: bar
  bar: [1, 2]
# Config for logging
# ------------------
# See http://docs.python.org/2.7/library/logging.config.html#configuration-dictionary-schema
logging:
  version: 1
  disable_existing_loggers: true
  # Configuring the default (root) logger is highly recommended
  root:
    level: !!python/name:logging.ERROR
    handlers: [logfile]
  loggers:
    # Logging from my application
    # Problems
    GPSProblem:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: problems.GPSProblem
    # Structure
    structure.CongestionGPSGraph:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: structure.CongestionGPSGraph
    structure.Graph:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: structure.Graph
    structure.GPSGraph:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: structure.GPSGraph
    # Simulator
    simulator.Simulator:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: simulator.Simulator
    simulator.FiniteHorizonSimulator:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: simulator.FiniteHorizonSimulator
    simulator.GPSSimulator:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: simulator.GPSSimulator
    simulator.utils.tools:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: simulator.utils.tools
    # Tests
    tests.StructureTest:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: tests.StructureTest
    tests.SimulatorTest:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: tests.SimulatorTest
    tests.ProblemsTest:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: tests.ProblemsTest
    # worker
    worker:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: worker
    # problem
    problems.Problem:
      level: !!python/name:logging.DEBUG
      handlers: [problemfile]
      qualname: problems.Problem
    SearchProblem:
      level: !!python/name:logging.DEBUG
      handlers: [problemfile]
      qualname: SearchProblem
    Heuristics:
      level: !!python/name:logging.DEBUG
      handlers: [problemfile]
      qualname: Heuristics
    problems.Models:
      level: !!python/name:logging.DEBUG
      handlers: [problemfile]
      qualname: problems.Models
    gurobipy:
      level: !!python/name:logging.DEBUG
      handlers: [problemfile]
      qualname: gurobipy
    #Comparator
    Comparator:
      level: !!python/name:logging.DEBUG
      handlers: [logfile]
      qualname: Comparator
  handlers:
    logfile:
      class: logging.FileHandler
      filename: logs/logs.log
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
    problemfile:
      class: logging.FileHandler
      filename: logs/problem.log
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
  formatters:
    simpleFormatter:
      class: !!python/name:logging.Formatter
      format: '%(asctime)s %(filename)-30s %(levelname)-8s: %(message)s'
      datefmt: '%Y-%m-%dT%T%Z'
graphml:
  traffic-colors:
    no-traffic: '#C3FE01'
    very-light-traffic: '#DCFE01'
    light-traffic: '#EDFE01'
    middle-light-traffic: '#F6FE01'
    middle-dense-traffic: '#FEF601'
    dense-traffic: '#FEBB01'
    very-dense-traffic: '#FE8801'
    traffic-jam: '#FE5E01'
    apocalyptic-traffic: '#FE0101'
  geometry:
    node-size: 30.0
  attributes:
    xmlns: "http://graphml.graphdrawing.org/xmlns"
    xmlns:java: "http://www.yworks.com/xml/yfiles-common/1.0/java"
    xmlns:sy: "http://www.yworks.com/xml/yfiles-common/markup/primitives/2.0"
    xmlns:x: "http://www.yworks.com/xml/yfiles-common/markup/2.0"
    xmlns:xsi: "http://www.w3.org/2001/XMLSchema-instance"
    xmlns:y: "http://www.yworks.com/xml/graphml"
    xmlns:yed: "http://www.yworks.com/xml/yed/3"
    xsi:schemaLocation: "http://graphml.graphdrawing.org/xmlns http://www.yworks.com/xml/schema/graphml/1.1/ygraphml.xsd"
  keys:
    d0:
      attr.name: "Description"
      attr.type: "string"
      for: "graph"
    d1:
      for: "port"
      yfiles.type: "portgraphics"
    d2:
      for: "port"
      yfiles.type: "portgeometry"
    d3:
      for: "port"
      yfiles.type: "portuserdata"
    d4:
      attr.name: "url"
      attr.type: "string"
      for: "node"
    d5:
      attr.name: "description"
      attr.type: "string"
      for: "node"
    d6:
      for: "node"
      yfiles.type: "nodegraphics"
    d7:
      for: "graphml"
      yfiles.type: "resources"
    d8:
      attr.name: "url"
      attr.type: "string"
      for: "edge"
    d9:
      attr.name: "description"
      attr.type: "string"
      for: "edge"
    d10:
      for: "edge"
      yfiles.type: "edgegraphics"
